# Generated by Django 2.2.19 on 2021-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=100, null=True)),
                ('booking_id', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(null=True)),
                ('from_station', models.CharField(max_length=100, null=True)),
                ('to_station', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('booking_date', models.DateField(auto_now_add=True, null=True)),
                ('passenger_name', models.CharField(blank=True, max_length=100)),
                ('passenger_age', models.IntegerField(default=0)),
                ('passenger_gender', models.CharField(blank=True, max_length=10)),
                ('journey_date', models.DateField(null=True)),
                ('seat_number', models.IntegerField(null=True)),
                ('seat_type', models.CharField(max_length=100, null=True)),
                ('fare', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
