# Generated by Django 2.2.19 on 2021-04-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirplaneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_type', models.CharField(max_length=20, null=True)),
                ('cost_per_km', models.FloatField(null=True)),
                ('fare_per_km', models.FloatField(null=True)),
                ('basic_cost', models.FloatField(null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveIntegerField(null=True)),
                ('load_factor', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EconomyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveIntegerField(null=True)),
                ('load_factor', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirstClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveIntegerField(null=True)),
                ('load_factor', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10, null=True)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airlines.Airline')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(null=True)),
                ('arrival_time', models.TimeField(null=True)),
                ('distance', models.PositiveIntegerField(null=True)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Schedule_day', to='airlines.Schedule')),
                ('from_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_airport', to='airlines.Airport')),
                ('to_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_airport', to='airlines.Airport')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='airlines.AirplaneType')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(null=True)),
                ('extra_requests', models.IntegerField(default=0)),
                ('flight_id', models.CharField(max_length=100, null=True)),
                ('departure_time', models.TimeField(null=True)),
                ('arrival_time', models.TimeField(null=True)),
                ('journey_date', models.DateField(null=True)),
                ('slug', models.SlugField(null=True)),
                ('first_class_seats', models.IntegerField(default=0)),
                ('business_class_seats', models.IntegerField(default=0)),
                ('economy_class_seats', models.IntegerField(default=0)),
                ('first_class_occupancy', models.CharField(blank=True, default='', max_length=200)),
                ('business_class_occupancy', models.CharField(blank=True, default='', max_length=200)),
                ('economy_class_occupancy', models.CharField(blank=True, default='', max_length=200)),
                ('first_class_occupancy_number', models.IntegerField(default=0)),
                ('business_class_occupancy_number', models.IntegerField(default=0)),
                ('economy_class_occupancy_number', models.IntegerField(default=0)),
                ('profits', models.IntegerField(default=0)),
                ('first_class_fare', models.IntegerField(default=0)),
                ('business_class_fare', models.IntegerField(default=0)),
                ('economy_class_fare', models.IntegerField(default=0)),
                ('airline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airlines.Airline')),
                ('from_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromAirport', to='airlines.Airport')),
                ('to_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toAirport', to='airlines.Airport')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planeType', to='airlines.AirplaneType')),
            ],
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='business_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_class', to='airlines.BusinessClass'),
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='economy_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='economy_class', to='airlines.EconomyClass'),
        ),
        migrations.AddField(
            model_name='airplanetype',
            name='first_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_class', to='airlines.FirstClass'),
        ),
    ]
